#! /bin/sh

# inicia el sxhkd para los shortcuts
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# inicia la polybar
~/.config/polybar/.launch.sh

# aplica el fondo de pantall
feh --bg-fill ~/.wallpapers/wallpaper.jpeg


xsetroot -cursor_name left_ptr &

# para la compatibilidad con java
wmname LG3D &

# para que el raton marque la pantalla focus
bspc config focus_follows_pointer true

# inicia el picom en modo experimental y pone los bordes de ventana redondeados
picom --experimental-backends &
bspc config border_width 0
